from xugu_dev import *
print('正在运行Pin类测试：Pin(123,321,None,"开发测试")')
pin=Pin(123,321,None,"开发测试")
print('正在运行Pin类测试：high(),low(),on(),off()')
pin.high()
pin.low()
pin.on()
pin.off()
print('正在运行ADC类测试：ADC(pin),read()')
ADC = ADC(pin)
ADC.read()
print('正在运行DAC类测试：DAC(pin),write(123)')
DAC = DAC(pin)
DAC.write(123)
print('正在运行舵机（Servo）类测试：Servo(20,"开发测试")')
servo = Servo(20,"开发测试")
print('正在运行舵机（Servo）类测试：angle(123),speed(123)')
servo.angle(123)
# servo.speed(123)
#上面那条会导致死循环，因此注释
print('正在运行I2C类测试：I2C(1,2,3,"开发测试"),read(1,2,3)')
I2C=I2C(1,2,3,"开发测试")
I2C.read(1,2,3)
    